fullnameOverride: blackbox-exporter

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

config:
  modules:
    http_2xx:
      prober: http
      timeout: 10s
      http:
        preferred_ip_protocol: ip4
        follow_redirects: true
        valid_status_codes: []
    http_reachable:
      prober: http
      timeout: 10s
      http:
        preferred_ip_protocol: ip4
        follow_redirects: false
        valid_status_codes: [200, 201, 202, 204, 301, 302, 303, 307, 308, 401, 403, 404, 405]
    tls_connect:
      prober: tcp
      timeout: 10s
      tcp:
        preferred_ip_protocol: ip4
        tls: true

serviceMonitor:
  enabled: false
