deployment:
  replicas: 2
  # Uso medido: ~107Mi.
  envoyGateway:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi

config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller

podDisruptionBudget:
  minAvailable: 1
