crds:
  enabled: false

grafana:
  enabled: false
  forceDeployDashboards: true

defaultRules:
  create: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 2
    retention: 120h
    resources:
      requests:
        cpu: 25m
        memory: 128Mi
      limits:
        memory: 256Mi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

prometheus:
  prometheusSpec:
    replicas: 2
    retention: 15d
    scrapeInterval: 30s
    evaluationInterval: 30s
    walCompression: true
    resources:
      requests:
        cpu: 200m
        memory: 1536Mi
      limits:
        memory: 3Gi
    enableAdminAPI: false
    enableRemoteWriteReceiver: true
    enableFeatures:
      - exemplar-storage
    exemplars:
      maxSize: 100000
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

prometheusOperator:
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 256Mi
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
  admissionWebhooks:
    patch:
      enabled: true

kube-state-metrics:
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 256Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
