deploymentMode: SingleBinary

loki:
  auth_enabled: false
  server:
    log_level: warn
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
  limits_config:
    retention_period: 14d

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  persistence:
    enabled: true
    size: 50Gi

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

gateway:
  enabled: true
  metrics:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

monitoring:
  serviceMonitor:
    enabled: true
  rules:
    enabled: true
  alerts:
    enabled: true
  dashboards:
    enabled: true

chunksCache:
  enabled: false

resultsCache:
  enabled: false

test:
  enabled: false

lokiCanary:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi

sidecar:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
