resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    memory: 400Mi

startupProbe:
  failureThreshold: 30
  periodSeconds: 5
livenessProbe:
  timeoutSeconds: 5
  failureThreshold: 5
readinessProbe:
  timeoutSeconds: 5
  failureThreshold: 5
