watchAnyNamespace: true

dashboards:
  enabled: true
  namespace: monitoring

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: null
    memory: 768Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30

generateNetworkPolicy: true
