tempo:
  retention: 168h
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
    storage:
      path: /var/tempo/generator/wal
    traces_storage:
      path: /var/tempo/generator/traces
  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

persistence:
  enabled: true
  size: 20Gi

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 1Gi
