tempo:
  retention: 168h
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

persistence:
  enabled: true
  size: 20Gi

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 1Gi
