dataStorage:
  enabled: true
  requestedSize: 5Gi
  keepPvc: true

deploymentStrategy: Recreate

valkeyConfig: |
  appendonly yes
  appendfsync everysec

auth:
  enabled: true
  usersExistingSecret: valkey-acl
  aclUsers:
    default:
      permissions: "~* &* +@all"
      passwordKey: default

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

metrics:
  enabled: true
  exporter:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
  serviceMonitor:
    enabled: true
