grafana.ini:
  server:
    root_url: https://grafana.cluster.example
  auth:
    disable_login_form: true
  auth.generic_oauth:
    enabled: true
    name: OIDC
    scopes: openid profile email groups offline_access
    auth_url: https://identity.cluster.example/oauth2/authorize
    token_url: https://identity.cluster.example/oauth2/token
    api_url: https://identity.cluster.example/userinfo
    use_pkce: true
    use_refresh_token: true
    role_attribute_strict: true
    role_attribute_path: contains(groups[*], 'replace-me-grafana-admins') && 'Admin' || contains(groups[*], 'replace-me-grafana-editors') && 'Editor' || contains(groups[*], 'replace-me-grafana-viewers') && 'Viewer' || 'None'
    allow_assign_grafana_admin: false
