apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  minAvailable: {{ .Values.cloudNativePg.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-redis-ha-haproxy
  namespace: argocd
spec:
  minAvailable: {{ .Values.argoCdRedis.minAvailable }}
  selector:
    matchLabels:
      app: redis-ha-haproxy
      release: argocd
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-redis-ha-server
  namespace: argocd
spec:
  minAvailable: {{ .Values.argoCdRedis.minAvailable }}
  selector:
    matchLabels:
      app: redis-ha
      release: argocd
