blank_issues_enabled: true
contact_links:
  - name: Questions and ideas
    url: https://github.com/pyahu/open-cluster-foundation/discussions
    about: Use Discussions for usage questions, ideas and show-and-tell.
