description: Small first installation with stateless platform services
profiles:
  edge: true
  certificates: true
  gitops: true
  postgresOperator: false
  messagingOperators: false
  observability: true
  cache: false
  identity: false
  secrets: false
  rabbitmqOperators: false
  kafka: false
  kafkaConnect: false
  highAvailability: false
  durableObservability: false
