apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infisical-postgres
  namespace: secrets
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-bookworm@sha256:702a5fd1e2de98afc72965149e90a633082df964087697b9cf89a81f21e343a7
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname
    nodeSelector:
      open-cluster-foundation.io/workload: database
    tolerations:
      - key: workload.open-cluster-foundation.io/database
        operator: Equal
        value: "true"
        effect: NoSchedule
  storage:
    size: 50Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: infisical
      owner: infisical
