apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: app-postgres-backup-store
  namespace: data
spec:
  configuration:
    destinationPath: s3://replace-me-cnpg-backups/app-postgres
    endpointURL: https://replace-me-namespace.compat.objectstorage.us-ashburn-1.oraclecloud.com
    s3Credentials:
      accessKeyId:
        name: cnpg-object-store
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-object-store
        key: SECRET_ACCESS_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-postgres-restore
  namespace: data
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-bookworm@sha256:702a5fd1e2de98afc72965149e90a633082df964087697b9cf89a81f21e343a7
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname
    nodeSelector:
      open-cluster-foundation.io/workload: database
    tolerations:
      - key: workload.open-cluster-foundation.io/database
        operator: Equal
        value: "true"
        effect: NoSchedule
  storage:
    size: 100Gi
  bootstrap:
    recovery:
      source: app-postgres-backup
  externalClusters:
    - name: app-postgres-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: app-postgres-backup-store
          serverName: app-postgres
