#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

OUTPUT_ROOT="${1:-${OCF_ROOT}/docs}"
REFERENCE_DIRECTORY="${OUTPUT_ROOT}/reference"
VERSIONS_FILE="${OCF_ROOT}/kubernetes/production-base/versions.yaml"
PROVIDER_CONTRACT_FILE="${OCF_ROOT}/terraform/provider-contract.yaml"
ENVIRONMENTS_DIRECTORY="${OCF_ROOT}/kubernetes/production-base/environments"
MISE_FILE="${OCF_ROOT}/mise.toml"

require_command yq
require_file "$VERSIONS_FILE"
require_file "$PROVIDER_CONTRACT_FILE"
require_file "$MISE_FILE"
mkdir -p "$REFERENCE_DIRECTORY"

markdown_code() {
  printf '\x60%s\x60' "$1"
}

COMPONENTS_FILE="${REFERENCE_DIRECTORY}/components.md"
{
  printf '%s\n\n' '# Component reference'
  printf '%s\n\n' 'This file is generated by scripts/generate-docs.sh. Edit kubernetes/production-base/versions.yaml or a local Chart.yaml, then regenerate it.'
  printf '| Component | Install method | Artifact | Pinned version | Related application versions |\n'
  printf '| --- | --- | --- | --- | --- |\n'
  while IFS=$'\t' read -r component_key display_name install_method artifact pinned_version application_versions; do
    [[ -n "$application_versions" ]] || application_versions='Not applicable'
    printf '| %s (%s) | %s | %s | %s | %s |\n' "$display_name" "$(markdown_code "$component_key")" "$(markdown_code "$install_method")" "$(markdown_code "$artifact")" "$(markdown_code "$pinned_version")" "$(markdown_code "$application_versions")"
  done < <(yq -r '.components | to_entries[] | [.key, .value.displayName, (.value.installMethod // "support-data"), (.value.chart // .value.repository // .value.manifest // .value.postgresPluginUrl // .value.exampleImage // "metadata"), (.value.chartVersion // .value.version // .value.commit // .value.imageTag // (.value.exampleImage | select(. != null) | split("@") | .[0] | split(":") | .[-1]) // "Not applicable"), ([.value.appVersion | select(. != null) | "application=" + ., .value.imageTag | select(. != null) | "image=" + ., .value.gatewayApiVersion | select(. != null) | "Gateway API=" + ., .value.kafkaVersion | select(. != null) | "Kafka=" + ., .value.kafkaConnectVersion | select(. != null) | "Kafka Connect=" + ., .value.prometheusVersion | select(. != null) | "Prometheus=" + ., .value.alertmanagerVersion | select(. != null) | "Alertmanager=" + .] | join(", "))] | @tsv' "$VERSIONS_FILE")
  for chart_file in "${OCF_ROOT}"/kubernetes/production-base/charts/*/Chart.yaml; do
    description="$(yq -r '.description' "$chart_file")"
    chart_version="$(yq -r '.version' "$chart_file")"
    app_version="$(yq -r '.appVersion' "$chart_file")"
    chart_directory="${chart_file%/Chart.yaml}"
    chart_path="charts/${chart_directory##*/charts/}"
    printf '| %s | %s | %s | %s | %s |\n' "$description" "$(markdown_code 'local-helm-chart')" "$(markdown_code "$chart_path")" "$(markdown_code "$chart_version")" "$(markdown_code "$app_version")"
  done
  printf '\n%s\n' 'The artifact and application columns reflect the fields maintained in the source catalog. A chart version and its upstream application version are separate compatibility contracts.'
} >"$COMPONENTS_FILE"

COMPATIBILITY_FILE="${REFERENCE_DIRECTORY}/compatibility.md"
minimum_kubernetes_version="$(yq -er '.minimumKubernetesVersion' "$VERSIONS_FILE")"
e2e_kubernetes_version="$(yq -er '.e2e.kubernetesVersion' "$VERSIONS_FILE")"
kind_node_image="$(yq -er '.e2e.kindNodeImage' "$VERSIONS_FILE")"
kind_version="$(yq -p=toml -o=json -er '.tools.kind' "$MISE_FILE")"
{
  printf '%s\n\n' '# Compatibility reference'
  printf '%s\n\n' 'This file is generated by scripts/generate-docs.sh. Edit the linked machine-readable sources, then regenerate it.'
  printf '%s\n\n' '## Kubernetes'
  printf '| Contract | Value | Source |\n'
  printf '| --- | --- | --- |\n'
  printf '| Minimum designed version | %s | %s |\n' "$(markdown_code "$minimum_kubernetes_version")" "$(markdown_code 'kubernetes/production-base/versions.yaml')"
  printf '| E2E Kubernetes version | %s | %s |\n' "$(markdown_code "$e2e_kubernetes_version")" "$(markdown_code 'kubernetes/production-base/versions.yaml')"
  printf '| E2E Kind version | %s | %s |\n' "$(markdown_code "$kind_version")" "$(markdown_code 'mise.toml')"
  printf '| E2E node image | %s | %s |\n' "$(markdown_code "$kind_node_image")" "$(markdown_code 'kubernetes/production-base/versions.yaml')"
  printf '\n%s\n\n' 'The minimum is a design contract. The pinned E2E row is the version installed and exercised by CI; it is stronger evidence and does not imply that every intermediate or newer Kubernetes version has been tested.'
  printf '%s\n\n' '## Cloud providers'
  printf '| Provider | Status | Module version | Live Kubernetes observation | Observed | Evidence mode |\n'
  printf '| --- | --- | --- | --- | --- | --- |\n'
  while IFS=$'\t' read -r provider status module_version live_version observed_at evidence_mode; do
    printf '| %s | %s | %s | %s | %s | %s |\n' "$(markdown_code "$provider")" "$(markdown_code "$status")" "$(markdown_code "$module_version")" "$(markdown_code "$live_version")" "$(markdown_code "$observed_at")" "$(markdown_code "$evidence_mode")"
  done < <(yq -r '.providers[] | [.name, .status, (.moduleVersion // "Not applicable"), (.evidence.kubernetesVersion // "Not applicable"), (.evidence.observedAt // "Not applicable"), (.evidence.mode // "Not applicable")] | @tsv' "$PROVIDER_CONTRACT_FILE")
  printf '\n%s\n\n' 'A read-only live observation proves API reachability and compatibility classification of an existing installation. It is not a destructive Terraform integration test or a guarantee for every OCI tenancy configuration.'
  printf '%s\n\n' '## Installation environments'
  printf '| Environment | Intended use | Enabled profiles |\n'
  printf '| --- | --- | --- |\n'
  for environment_file in "$ENVIRONMENTS_DIRECTORY"/*.yaml; do
    environment="${environment_file##*/}"
    environment="${environment%.yaml}"
    description="$(yq -er '.description' "$environment_file")"
    profiles="$(yq -r '.profiles | to_entries | map(select(.value == true) | .key) | join(", ")' "$environment_file")"
    printf '| %s | %s | %s |\n' "$(markdown_code "$environment")" "$description" "$(markdown_code "$profiles")"
  done
  printf '\n%s\n' 'Automatic environment selection and state transitions are defined in [installation compatibility](../compatibility.md).'
} >"$COMPATIBILITY_FILE"

log "generated ${COMPONENTS_FILE#"${OCF_ROOT}"/} and ${COMPATIBILITY_FILE#"${OCF_ROOT}"/}"
