name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scripts:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c
        with:
          install_args: shellcheck
      - run: mise run ci:scripts

  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c
        with:
          install_args: terraform tflint yq ripgrep
      - run: mise run ci:terraform

  kubernetes:
    name: kubernetes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c
        with:
          install_args: helm helmfile kubeconform
      - run: mise run ci:kubernetes

  supply-chain:
    name: supply-chain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c
        with:
          install_args: trivy yq ripgrep
      - run: mise run ci:supply-chain
